### ISSUE TITLE
Open Multiple Sidebar items

### ISSUE THREAD

**Issue by chintuyadavsara** [alexey-gladilin/ng-sidebar-accordion#1]
Hi @alexey-gladilin 

I have tried this npm package and it is very impressive, i have a question here on how to do this.
Lets say I have two items in the sidebar and I want to remain open the sidebar items, i dont want to collapse the items when another is clicked.

Could you please let me know, how we do this.

Thanks

**Comment by alexey-gladilin** [comment]
Hi  @chintuyadavsara 

I published an updated version of the component for Angular 12. Added the ability to pin the sidebar. The sidebar has an additional property "pinned".
An example of how the new property works can be found in [demo](https://alexey-gladilin.github.io/ng-sidebar-accordion/)
```typescript
<ng-sidebar #sidebar position="right" [opened]="true" [pinned]="true">
    <ng-sidebar-header>
      <div class="app__header-pinned">
        <div
          class="fa fa-thumb-tack"
          [class.pinned]="sidebar.pinned"
          (click)="onPinnedClick($event, sidebar)"
        ></div>
        <div>
          <div>right-pane0-header-row1 {{ getMode("right") }}</div>
          <div>right-pane0-header-row2</div>
        </div>
      </div>
    </ng-sidebar-header>
    <ng-sidebar-content> right-pane0-content </ng-sidebar-content>
  </ng-sidebar>
```

**Comment by chintuyadavsara** [comment]
This helps, Thanks @alexey-gladilin
