### ISSUE TITLE
Can't import the named export ... from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by Ijaz-Tufail** [alexey-gladilin/ng-sidebar-accordion#2]
Following exceptions occured while import in module in Angular 11. Please help

`Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 27:346-372
Can't import the named export 'ChangeDetectionStrategy' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 33:37-60
Can't import the named export 'ChangeDetectionStrategy' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 450:8203-8229
Can't import the named export 'ChangeDetectionStrategy' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 489:22-45
Can't import the named export 'ChangeDetectionStrategy' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 619:38-64
Can't import the named export 'ChangeDetectionStrategy' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 628:37-60
Can't import the named export 'ChangeDetectionStrategy' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 705:44-70
Can't import the named export 'ChangeDetectionStrategy' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 715:37-60
Can't import the named export 'ChangeDetectionStrategy' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 763:397-423
Can't import the named export 'ChangeDetectionStrategy' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 769:37-60
Can't import the named export 'ChangeDetectionStrategy' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 795:444-470
Can't import the named export 'ChangeDetectionStrategy' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 801:37-60
Can't import the named export 'ChangeDetectionStrategy' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 413:187-207
Can't import the named export 'ChangeDetectorRef' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 490:83-103
Can't import the named export 'ChangeDetectorRef' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 825:45-57
mCan't import the named export 'CommonModule' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 831:151-163
Can't import the named export 'CommonModule' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 835:30-42
Can't import the named export 'CommonModule' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 29:18-27
Can't import the named export 'Component' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 452:18-27
Can't import the named export 'Component' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 621:18-27
Can't import the named export 'Component' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 707:18-27
Can't import the named export 'Component' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 765:18-27
Can't import the named export 'Component' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 797:18-27
Can't import the named export 'Component' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 517:22-37
Can't import the named export 'ContentChildren' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 413:161-174
Can't import the named export 'ElementRef' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 490:58-71
Can't import the named export 'ElementRef' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 762:202-215
Can't import the named export 'ElementRef' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 774:34-47
Can't import the named export 'ElementRef' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 8:30-42
Can't import the named export 'EventEmitter' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 9:34-46
Can't import the named export 'EventEmitter' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 51:41-53
Can't import the named export 'EventEmitter' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 52:39-51
Can't import the named export 'EventEmitter' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 53:39-51
Can't import the named export 'EventEmitter' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 525:33-45
Can't import the named export 'EventEmitter' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 526:36-48
Can't import the named export 'EventEmitter' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 527:36-48
Can't import the named export 'EventEmitter' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 528:32-44
Can't import the named export 'EventEmitter' from non EcmaScript module (only default export is available)

[39mError: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 675:27-39
Can't import the named export 'EventEmitter' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 676:30-42
Can't import the named export 'EventEmitter' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 677:30-42
Can't import the named export 'EventEmitter' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 491:22-33
Can't import the named export 'HostBinding' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 496:22-33
Can't import the named export 'HostBinding' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 501:22-33
Can't import the named export 'HostBinding' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 506:22-33
Can't import the named export 'HostBinding' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 637:22-33
Can't import the named export 'HostBinding' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 642:22-33
Can't import the named export 'HostBinding' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 647:22-33
Can't import the named export 'HostBinding' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 652:22-33
Can't import the named export 'HostBinding' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 663:22-33
Can't import the named export 'HostBinding' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 722:22-33
Can't import the named export 'HostBinding' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 727:22-33
Can't import the named export 'HostBinding' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 776:22-33
Can't import the named export 'HostBinding' from non EcmaScript module (only default export is available)

mError: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 781:22-33
Can't import the named export 'HostBinding' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 808:22-33
Can't import the named export 'HostBinding' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 813:22-33
Can't import the named export 'HostBinding' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 736:22-34
Can't import the named export 'HostListener' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 739:22-34
Can't import the named export 'HostListener' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 742:22-34
Can't import the named export 'HostListener' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 40:22-27
Can't import the named export 'Input' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 42:22-27
Can't import the named export 'Input' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 494:22-27
Can't import the named export 'Input' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 499:22-27
Can't import the named export 'Input' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 504:22-27
Can't import the named export 'Input' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 509:22-27
Can't import the named export 'Input' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 635:22-27
Can't import the named export 'Input' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 640:22-27
Can't import the named export 'Input' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 645:22-27
Can't import the named export 'Input' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 650:22-27
Can't import the named export 'Input' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 666:22-27
Can't import the named export 'Input' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 668:22-27
Can't import the named export 'Input' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 725:22-27
Can't import the named export 'Input' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 779:22-27
Can't import the named export 'Input' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 811:22-27
Can't import the named export 'Input' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 450:7971-7981
Can't import the named export 'NgClass' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 450:8112-8119
Can't import the named export 'NgIf' from non EcmaScript module (only default export is available)
[39m
Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 833:18-26
Can't import the named export 'NgModule' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 450:8046-8056
Can't import the named export 'NgStyle' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 632:30-38
Can't import the named export 'Optional' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 719:30-38
Can't import the named export 'Optional' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 773:30-38
Can't import the named export 'Optional' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 805:30-38
Can't import the named export 'Optional' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 36:22-28
Can't import the named export 'Output' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 38:22-28
Can't import the named export 'Output' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 511:22-28
Can't import the named export 'Output' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 513:22-28
Can't import the named export 'Output' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 515:22-28
Can't import the named export 'Output' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 655:22-28
Can't import the named export 'Output' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 657:22-28
Can't import the named export 'Output' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 659:22-28
Can't import the named export 'Output' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 661:22-28
Can't import the named export 'Output' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 730:22-28
Can't import the named export 'Output' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 732:22-28
Can't import the named export 'Output' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 734:22-28
Can't import the named export 'Output' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 26:161-179
Can't import the named export 'ɵɵFactoryTarget' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 413:220-238
Can't import the named export 'ɵɵFactoryTarget' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 615:197-215
Can't import the named export 'ɵɵFactoryTarget' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 700:200-218
Can't import the named export 'ɵɵFactoryTarget' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 762:228-246
Can't import the named export 'ɵɵFactoryTarget' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 794:229-247
Can't import the named export 'ɵɵFactoryTarget' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 819:157-175
Can't import the named export 'ɵɵFactoryTarget' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 28:0-27
Can't import the named export 'ɵɵngDeclareClassMetadata' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 451:0-27
Can't import the named export 'ɵɵngDeclareClassMetadata' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 620:0-27
Can't import the named export 'ɵɵngDeclareClassMetadata' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 706:0-27
Can't import the named export 'ɵɵngDeclareClassMetadata' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 764:0-27
Can't import the named export 'ɵɵngDeclareClassMetadata' from non EcmaScript module (only default export is available)
1m
Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 796:0-27
Can't import the named export 'ɵɵngDeclareClassMetadata' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 832:0-27
Can't import the named export 'ɵɵngDeclareClassMetadata' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 27:32-55
Can't import the named export 'ɵɵngDeclareComponent' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 414:33-56
Can't import the named export 'ɵɵngDeclareComponent' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 616:24-47
Can't import the named export 'ɵɵngDeclareComponent' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 701:30-53
Can't import the named export 'ɵɵngDeclareComponent' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 763:31-54
Can't import the named export 'ɵɵngDeclareComponent' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 795:40-63
Can't import the named export 'ɵɵngDeclareComponent' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 26:32-53
Can't import the named export 'ɵɵngDeclareFactory' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 413:33-54
Can't import the named export 'ɵɵngDeclareFactory' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 615:24-45
Can't import the named export 'ɵɵngDeclareFactory' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 700:30-51
Can't import the named export 'ɵɵngDeclareFactory' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 762:31-52
Can't import the named export 'ɵɵngDeclareFactory' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 794:40-61
Can't import the named export 'ɵɵngDeclareFactory' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 819:30-51
Can't import the named export 'ɵɵngDeclareFactory' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 831:30-52
Can't import the named export 'ɵɵngDeclareInjector' from non EcmaScript module (only default export is available)

Error: ./node_modules/ng-sidebar-accordion/fesm2015/ng-sidebar-accordion.mjs 820:30-52
Can't import the named export 'ɵɵngDeclareNgModule' from non EcmaScript module (only default export is available)`

**Comment by alexey-gladilin** [comment]
Hi!
I don't have an assembly for 11 Angular.
There are several options here:
- take the source code of the component and build a project for the 11th version of Angular
- in your project, upgrade the Angular version to a newer version
